server:
  port: 9000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/business?useSSL=false
    username: root
    password: tangfang007
    max-active: 20
    max-wait: 6000
    min-idle: 1
    test-on-borrow: true
    test-on-return: true

mybatis:
  mapper-locations: classpath*:com/aohe/mapper/*Mapper.xml
