package com.aohe.pojo;

import java.util.Date;

public class PayInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_payinfo.id
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_payinfo.user_id
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_payinfo.order_no
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_payinfo.pay_platform
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private Integer payPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_payinfo.platform_number
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private String platformNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_payinfo.platform_status
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private String platformStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_payinfo.create_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_payinfo.update_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_payinfo.id
     *
     * @return the value of aohe_payinfo.id
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_payinfo.id
     *
     * @param id the value for aohe_payinfo.id
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_payinfo.user_id
     *
     * @return the value of aohe_payinfo.user_id
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_payinfo.user_id
     *
     * @param userId the value for aohe_payinfo.user_id
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_payinfo.order_no
     *
     * @return the value of aohe_payinfo.order_no
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_payinfo.order_no
     *
     * @param orderNo the value for aohe_payinfo.order_no
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_payinfo.pay_platform
     *
     * @return the value of aohe_payinfo.pay_platform
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public Integer getPayPlatform() {
        return payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_payinfo.pay_platform
     *
     * @param payPlatform the value for aohe_payinfo.pay_platform
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setPayPlatform(Integer payPlatform) {
        this.payPlatform = payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_payinfo.platform_number
     *
     * @return the value of aohe_payinfo.platform_number
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public String getPlatformNumber() {
        return platformNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_payinfo.platform_number
     *
     * @param platformNumber the value for aohe_payinfo.platform_number
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setPlatformNumber(String platformNumber) {
        this.platformNumber = platformNumber == null ? null : platformNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_payinfo.platform_status
     *
     * @return the value of aohe_payinfo.platform_status
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public String getPlatformStatus() {
        return platformStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_payinfo.platform_status
     *
     * @param platformStatus the value for aohe_payinfo.platform_status
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setPlatformStatus(String platformStatus) {
        this.platformStatus = platformStatus == null ? null : platformStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_payinfo.create_time
     *
     * @return the value of aohe_payinfo.create_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_payinfo.create_time
     *
     * @param createTime the value for aohe_payinfo.create_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_payinfo.update_time
     *
     * @return the value of aohe_payinfo.update_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_payinfo.update_time
     *
     * @param updateTime the value for aohe_payinfo.update_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}