package com.aohe.pojo;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.util.Date;

@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.id
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.username
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.password
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.userpic
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private String userpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.email
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.phone
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.question
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.answer
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.role
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.create_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.update_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aohe_user.ip
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.id
     *
     * @return the value of aohe_user.id
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.id
     *
     * @param id the value for aohe_user.id
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.username
     *
     * @return the value of aohe_user.username
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.username
     *
     * @param username the value for aohe_user.username
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.password
     *
     * @return the value of aohe_user.password
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.password
     *
     * @param password the value for aohe_user.password
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.userpic
     *
     * @return the value of aohe_user.userpic
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public String getUserpic() {
        return userpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.userpic
     *
     * @param userpic the value for aohe_user.userpic
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setUserpic(String userpic) {
        this.userpic = userpic == null ? null : userpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.email
     *
     * @return the value of aohe_user.email
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.email
     *
     * @param email the value for aohe_user.email
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.phone
     *
     * @return the value of aohe_user.phone
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.phone
     *
     * @param phone the value for aohe_user.phone
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.question
     *
     * @return the value of aohe_user.question
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.question
     *
     * @param question the value for aohe_user.question
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.answer
     *
     * @return the value of aohe_user.answer
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.answer
     *
     * @param answer the value for aohe_user.answer
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.role
     *
     * @return the value of aohe_user.role
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.role
     *
     * @param role the value for aohe_user.role
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.create_time
     *
     * @return the value of aohe_user.create_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.create_time
     *
     * @param createTime the value for aohe_user.create_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.update_time
     *
     * @return the value of aohe_user.update_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.update_time
     *
     * @param updateTime the value for aohe_user.update_time
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aohe_user.ip
     *
     * @return the value of aohe_user.ip
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aohe_user.ip
     *
     * @param ip the value for aohe_user.ip
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}