package com.aohe.dao;

import com.aohe.pojo.Category;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_category
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_category
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_category
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_category
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_category
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_category
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKey(Category record);
}