package com.aohe.dao;

import com.aohe.pojo.OrderItem;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_order_item
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_order_item
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_order_item
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_order_item
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_order_item
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_order_item
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKey(OrderItem record);
}