package com.aohe.dao;

import com.aohe.pojo.PayInfo;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_payinfo
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_payinfo
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_payinfo
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insertSelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_payinfo
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    PayInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_payinfo
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKeySelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_payinfo
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKey(PayInfo record);
}