package com.aohe.dao;

import com.aohe.pojo.Product;
import com.aohe.pojo.ProductWithBLOBs;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_product
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_product
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insert(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_product
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insertSelective(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_product
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    ProductWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_product
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKeySelective(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_product
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_product
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKey(Product record);
}