package com.aohe.dao;

import com.aohe.pojo.Shipping;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_shipping
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_shipping
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_shipping
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insertSelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_shipping
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_shipping
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKeySelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_shipping
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKey(Shipping record);
}