package com.aohe.dao;

import com.aohe.pojo.User;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_user
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_user
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_user
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_user
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    User selectByPrimaryKey(Integer id);

    Integer selectByUserName(@Param("username") String username);
    Integer selectByPhone(@Param("phone") String phone);
    Integer selectByEmail(@Param("email") String email);

    User selectByUserNameAndPassword(@Param("username") String username,@Param("password") String password);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_user
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aohe_user
     *
     * @mbg.generated Thu May 14 14:37:23 CST 2020
     */
    int updateByPrimaryKey(User record);
}